title: "Hillsborough Safety Services 3D"
description: "An interactive dashboard visualizing emergency services accessibility."
theme: minima
baseurl: ""  # Adjust if your site is published in a subdirectory